#!/bin/sh

#初始化函数
load_config(){

user_group_web="web"
web_path="web"
web_log_path="weblog"
web_resource_path="webresource"

PHP_Version="`/usr/local/php/bin/php-config --version`"

###################主要安装包设置###################
run_path="/usr/local"


boost_filename="boost_1_66_0"
nginx_filename="nginx-1.8.1"
mysql_filename="mysql-5.6.43"
mysql80_filename="mysql-8.0.11"
apache_filename="httpd-2.4.38"
php_filename="php-5.6.19"
php54_filename="php-5.4.35"
php73_filename="php-7.3.3"
iconv_filename="libiconv-1.15"
cmake_filename="cmake-3.1.0"
svn_filename="subversion-1.8.13"
apr_filename="apr-1.6.3"
apr_util_filename="apr-util-1.6.1"
pcre_filename="pcre-8.39"
jemalloc_filename="jemalloc-5.0.1"

boost_pag="boost_1_66_0.tar.bz2"
nginx_pag="nginx-1.8.1.tar.gz"
mysql_pag="mysql-5.6.43.tar.gz"
mysql80_pag="mysql-8.0.11.tar.gz"
apache_pag="httpd-2.4.38.tar.gz"
php_pag="php-5.6.19.tar.gz"
php54_pag="php-5.4.35.tar.gz"
php73_pag="php-7.3.3.tar.gz"
iconv_pag="libiconv-1.15.tar.gz"
cmake_pag="cmake-3.1.0.tar.gz"
svn_pag="subversion-1.8.13.tar.gz"
apr_pag="apr-1.6.3.tar.bz2"
apr_util_pag="apr-util-1.6.1.tar.bz2"
pcre_pag="pcre-8.39.tar.bz2"
jemalloc_pag="jemalloc-5.0.1.tar.bz2"

boost_path="$install_dir/$boost_filename"
nginx_path="$install_dir/$nginx_filename/"
mysql_path="$install_dir/$mysql_filename/"
mysql80_path="$install_dir/$mysql80_filename/"
apache_path="$install_dir/$apache_filename/"
php_path="$install_dir/$php_filename/"
php54_path="$install_dir/$php54_filename/"
php73_path="$install_dir/$php73_filename/"
iconv_path="$install_dir/$iconv_filename/"
cmake_path="$install_dir/$cmake_filename/"
svn_path="$install_dir/$svn_filename/"
apr_path="$install_dir/$apr_filename/"
apr_util_path="$install_dir/$apr_util_filename/"
pcre_path="$install_dir/$pcre_filename/"
jemalloc_path="$install_dir/$jemalloc_filename/"

nginx_run_path="$run_path/nginx"
mysql_run_path="$run_path/mysql"
mysql80_run_path="$run_path/mysql"
apache_run_path="$run_path/apache"
php_run_path="$run_path/php"

cmake_run_path="$run_path/cmake"
iconv_run_path="$run_path/iconv"
svn_run_path="$run_path/subversion"
apr_run_path="$run_path/apr"
apr_util_run_path="$run_path/apr-util"
pcre_run_path="$run_path/pcre"
jemalloc_run_path="$run_path/jemalloc"
#--------------config----------------
nginx_conf="$conf_dir/ng"
mysql_conf="$conf_dir/mysql"
apache_conf="$conf_dir/apache"
php_conf="$conf_dir/php"
svn_conf="$conf_dir/svn"
memcached_conf="$conf_dir/memcached"
redis_conf="$conf_dir/redis"
}
